version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    command: start-dev
    #entrypoint: kc.sh start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc://db:3306/keycloak
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORTD=123456
    depends_on:
      db:
        condition: service_healthy

  db:
    image: osdeving/mysql-dev
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
      #start_period: 30s


# docker run --name dev-keycloak -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:22.0 start-dev